# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1242, 842)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 40, 531, 471))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_1 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_1.setContentsMargins(0, 0, 0, 0)
        self.formLayout_1.setObjectName("formLayout_1")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(650, 40, 571, 471))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 10, 121, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(860, 10, 161, 20))
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 550, 551, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(640, 550, 581, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 5, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 220, 61, 61))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1242, 20))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuoperation = QtWidgets.QMenu(self.menubar)
        self.menuoperation.setObjectName("menuoperation")
        self.menuoperation_right = QtWidgets.QMenu(self.menubar)
        self.menuoperation_right.setObjectName("menuoperation_right")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_load = QtWidgets.QAction(MainWindow)
        self.action_load.setObjectName("action_load")
        self.actiondisplay_cuboid_result = QtWidgets.QAction(MainWindow)
        self.actiondisplay_cuboid_result.setObjectName("actiondisplay_cuboid_result")
        self.action_display_original_pc = QtWidgets.QAction(MainWindow)
        self.action_display_original_pc.setObjectName("action_display_original_pc")
        self.actionpredict = QtWidgets.QAction(MainWindow)
        self.actionpredict.setObjectName("actionpredict")
        self.actionhh = QtWidgets.QAction(MainWindow)
        self.actionhh.setObjectName("actionhh")
        self.actiontrans_robot_coordinates = QtWidgets.QAction(MainWindow)
        self.actiontrans_robot_coordinates.setObjectName("actiontrans_robot_coordinates")
        self.actionfilter_bolts = QtWidgets.QAction(MainWindow)
        self.actionfilter_bolts.setObjectName("actionfilter_bolts")
        self.actionestimate_Rx_Ry_Rz = QtWidgets.QAction(MainWindow)
        self.actionestimate_Rx_Ry_Rz.setObjectName("actionestimate_Rx_Ry_Rz")
        self.action_display_cuboid_pc = QtWidgets.QAction(MainWindow)
        self.action_display_cuboid_pc.setObjectName("action_display_cuboid_pc")
        self.action_cubiod_prediction = QtWidgets.QAction(MainWindow)
        self.action_cubiod_prediction.setObjectName("action_cubiod_prediction")
        self.action_bolts_position = QtWidgets.QAction(MainWindow)
        self.action_bolts_position.setObjectName("action_bolts_position")
        self.action_motor_orientation = QtWidgets.QAction(MainWindow)
        self.action_motor_orientation.setObjectName("action_motor_orientation")
        self.action_to_robote_coordinates = QtWidgets.QAction(MainWindow)
        self.action_to_robote_coordinates.setObjectName("action_to_robote_coordinates")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("actionsave")
        self.menufile.addAction(self.action_load)
        self.menufile.addAction(self.action_save)
        self.menuoperation.addAction(self.action_display_original_pc)
        self.menuoperation.addAction(self.action_display_cuboid_pc)
        self.menuoperation_right.addAction(self.action_cubiod_prediction)
        self.menuoperation_right.addAction(self.action_bolts_position)
        self.menuoperation_right.addAction(self.action_motor_orientation)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuoperation.menuAction())
        self.menubar.addAction(self.menuoperation_right.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "original point cloud"))
        self.label.adjustSize()
        self.label_2.setText(_translate("MainWindow", "the predicted point cloud"))
        self.label_2.adjustSize()
        self.label_4.setText(_translate("MainWindow", "Number of points:"))
        self.pushButton.setText(_translate("MainWindow", "cut\n"
"&&\n"
"seg."))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menuoperation.setTitle(_translate("MainWindow", "operation_left"))
        self.menuoperation_right.setTitle(_translate("MainWindow", "operation_right"))
        self.action_load.setText(_translate("MainWindow", "load"))
        self.actiondisplay_cuboid_result.setText(_translate("MainWindow", "display cuboid pc"))
        self.action_display_original_pc.setText(_translate("MainWindow", "display original pc"))
        self.actionpredict.setText(_translate("MainWindow", "predict"))
        self.actionpredict.setStatusTip(_translate("MainWindow", "start  to calculate"))
        self.actionhh.setText(_translate("MainWindow", "hh"))
        self.actiontrans_robot_coordinates.setText(_translate("MainWindow", "trans_robot_coordinates"))
        self.actionfilter_bolts.setText(_translate("MainWindow", "filter_bolts"))
        self.actionestimate_Rx_Ry_Rz.setText(_translate("MainWindow", "estimate_Rx_Ry_Rz"))
        self.action_display_cuboid_pc.setText(_translate("MainWindow", "display cuboid pc"))
        self.action_cubiod_prediction.setText(_translate("MainWindow", "cubiod_prediction"))
        self.action_cubiod_prediction.setStatusTip(_translate("MainWindow", "start to calculate"))
        self.action_bolts_position.setText(_translate("MainWindow", "bolts_position"))
        self.action_motor_orientation.setText(_translate("MainWindow", "motor_orientation"))
        self.action_to_robote_coordinates.setText(_translate("MainWindow", "to_robot_coordinates"))
        self.action_save.setText(_translate("MainWindow", "save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

